name: dev-ci
on:
  push:
    branches:
      - main
jobs:
  deploy_ghpages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.16.0
      - run: npm install -g yarn@1.22.19

      - name: yarn install and build
        run: |
          yarn
          yarn build

      - name: deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.MY_HOST }} # 服务器IP（需要在GitHub上自行配置对应的secret）
          user: ${{ secrets.MY_USER }} # 服务器用户名
          pass: ${{ secrets.MY_PASS }} # 服务器密码
          connect_timeout: 10s
          first_ssh: | # 目标路径（服务器）
            rm -rf /var/www/zhuxb-blog
            mkdir -p /var/www/zhuxb-blog
          scp: |
            './out/*' => /var/www/zhuxb-blog
