name: dev-ci
on:
  push:
    branches:
      - main
jobs:
  deploy_ghpages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.12.0
      - run: npm install -g yarn

      - name: yarn install and build
        run: |
          yarn
          yarn build

      - name: deploy
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.MY_HOST }} # 服务器IP（需要在GitHub上自行配置对应的secret）
          user: ${{ secrets.MY_USER }} # 服务器用户名
          pass: ${{ secrets.MY_PASS }} # 服务器密码
          connect_timeout: 10s
          local: "./out/*" # 源路径（工作流）
          remote: /var/www/zhuxb-blog # 目标路径（服务器）

      - name: Executing remote ssh commands
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.MY_HOST }} # 服务器IP（需要在GitHub上自行配置对应的secret
          user: ${{ secrets.MY_USER }} # 服务器用户名
          pass: ${{ secrets.MY_PASS }} # 服务器密码
          connect_timeout: 10s
          first_ssh: |
            cd /var/www/zhuxb-blog
