name: dev-ci
on:
  push:
    branches:
      - main
jobs:
  deploy_ghpages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.16.0
      - run: npm install -g yarn@1.22.19
      - name: Record deploy start time
        id: deploy_start
        run: echo "deploy_start=$(date +%s)" >> $GITHUB_ENV
      - name: yarn install and build
        id: build_step # 标记构建步骤ID用于状态获取
        run: |
          yarn
          yarn export
      - name: Upload dist files
        id: deploy_step # 标记部署步骤ID用于状态获取
        uses: appleboy/scp-action@v1.0.0
        with:
            host: ${{ secrets.MY_HOST }}
            username: ${{ secrets.MY_USER }}
            password: ${{ secrets.MY_PASS }}
            port: 22
            source: 'out/*'
            target: /var/www/zhuxb-blog
            rm: true
            strip_components: 1

      - name: Record commit info
        id: commit_info
        run: |
            echo "commit_hash=$(echo "${GITHUB_SHA}" | cut -c1-7)" >> $GITHUB_ENV
            echo "commit_message=$(git log -1 --pretty=%B | head -n 1)" >> $GITHUB_ENV

      - name: Record deploy end time
        id: deploy_end
        run: echo "deploy_end=$(date +%s)" >> $GITHUB_ENV

      - name: Calculate duration
        id: duration
        run: echo "duration=$(( ${DEPLOY_END} - ${DEPLOY_START} ))" >> $GITHUB_ENV
        env:
            DEPLOY_START: ${{ env.deploy_start }}
            DEPLOY_END: ${{ env.deploy_end }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Notify Feishu
        if: always()
        run: |
            # 获取构建/部署状态（英文表述）
            BUILD_STATUS=$(if [ "${{ steps.build_step.outcome }}" == 'success' ]; then echo "✅ 构建成功"; else echo "❌ 构建失败"; fi)
            DEPLOY_STATUS=$(if [ "${{ steps.deploy_step.outcome }}" == 'success' ]; then echo "✅ 部署成功"; else echo "❌ 部署失败"; fi)

            # 转换时间为北京时间（UTC+8）
            START_BEIJING=$(TZ=Asia/Shanghai date -d "@${{ env.deploy_start }}" +"%Y-%m-%d %H:%M:%S")
            END_BEIJING=$(date -d @${{ env.deploy_end }} +"%Y-%m-%d %H:%M:%S +0800")**

            # 格式化耗时（小时:分钟:秒）
            DURATION=${duration:-0}  # 若duration未定义，默认0秒
            HOURS=$(( DURATION / 3600 ))
            MINUTES=$(( (DURATION % 3600) / 60 ))
            SECONDS=$(( DURATION % 60 ))
            DURATION_HMS=$(printf '%02d:%02d:%02d' $HOURS $MINUTES $SECONDS)

            PAYLOAD=$(jq -n \
              --arg build_status "$BUILD_STATUS" \
              --arg deploy_status "$DEPLOY_STATUS" \
              --arg start_time "$START_BEIJING" \
              --arg end_time "$END_BEIJING" \
              --arg duration "$DURATION_HMS (${{ env.duration }} s)" \
              --arg branch "${GITHUB_REF#refs/heads/}" \
              --arg commit_hash "${{ env.commit_hash }}" \
              --arg commit_message "${{ env.commit_message }}" \
              --arg server "${{ secrets.MY_HOST }}" \
              '{
                msg_type: "post",
                content: {
                  title: "[Github Action]部署通知",
                  project: "- **项目名**: next-zhuxb-blog",
                  build_status: "- **构建状态**: \($build_status)",
                  deploy_status: "- **部署状态**: \($deploy_status)",
                  branch: "- **分支**: \($branch)",
                  commit: "- **Commit**: \($commit_hash) (\($commit_message))",
                  startTime: "- **开始时间**: \($start_time)",
                  duration: "- **耗时**: \($duration)"
                }
              }')

            # 发送飞书通知
            curl -X POST "${{ secrets.FEISHU_WEBHOOK_URL }}" \
                  -H "Content-Type: application/json" \
                  -d "${PAYLOAD}"
